# Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional
array object, various derived objects (arrays and matrices),  for
fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O  and much more.
At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous
data types, with many operations being performed in compiled code for performance. There are several important
differences between NumPy arrays and the standard Python sequences:


• NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the
size of an ndarray will create a new array and delete the original.


• The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in
memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays
of different sized elements.


• NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically,
such operations are executed more efficiently and with less code than is possible using Python’s built-in
sequences.

• A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though
these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing,
and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most)
of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence
types is insufficient - one also needs to know how to use NumPy arrays.

In [3]:
a = [1,2,3,4]
b = [5,6,7,8]

In [4]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [5]:
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])
print(c)

[5, 12, 21, 32]


In [6]:
c = a*b # when i tried doing it in this way it was not supporting

TypeError: can't multiply sequence by non-int of type 'list'

In [7]:
import numpy as np
a1 = np.array(a)
b1 = np.array(b)
c = a1*b1

# that means when i converted them onto the array 

In [7]:
c


array([ 5, 12, 21, 32])

In [9]:
import numpy as np
a18 = np.array([1,2,3,4,5,6], dtype = float)
a18

array([1., 2., 3., 4., 5., 6.])

In [9]:
a2 = [1,2,3,4]
array1 = np.array(a2)
type(array1)

numpy.ndarray

In [10]:
a = [1,2,3,4]
b = [5,6,7,8]
a1 = np.array(a)
b1 = np.array(b)

In [11]:
a1 + b1

array([ 6,  8, 10, 12])

In [12]:
b2 = [[1,2,3], [3,4,5],[6,7,8]]
np.array(b2)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
a1*b1

array([ 5, 12, 21, 32])

In [14]:
import numpy as np

In [15]:
b = [[1,2,3,4],9]

In [16]:
b22 = np.array(b)

In [17]:
b22

array([list([1, 2, 3, 4]), 9], dtype=object)

In [18]:
tup = (1,2,3)
type(tup)

tuple

In [49]:
a = [[1,2,3,4],[1,2,3,4]]
np.array(a)

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [19]:
a = [1,2.5,3]

a1 = np.array(a)
# notice the difference

a1
#len(a1)

array([1. , 2.5, 3. ])

In [20]:
a1.dtype

dtype('float64')

In [21]:
b = [1,2,3]
b1 = np.array(b)
b1
b1.dtype

dtype('int32')

In [3]:
import numpy as np

In [4]:
my_list = [1,2,3,4]

In [5]:
a111 = np.array(my_list)

In [10]:
type(a111) 

numpy.ndarray

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3, 4])

In [9]:
a = [[1,2]]
np.array(a)

array([[1, 2]])

In [11]:
b = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
b

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
b64 = np.array(b)

b64

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Built in Methods
there are lots of methods to generate arrays

 # arange
returns evenly spaced values within a given interval

In [31]:
import numpy as np

In [ ]:
np.arange()

In [32]:
a = np.arange(10,50,5)
a

array([10, 15, 20, 25, 30, 35, 40, 45])

here we can note that if we have given an interval as 0 to 10 10 will not be included in the final output
let us see some more example

In [33]:
np.arange(-4,61)

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
np.arange(80)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [36]:
np.arange(0,11),
np.arange(0,20,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
np.arange(0,0)

array([], dtype=int32)

In [38]:
my_list1 = [ "chatur", 3, "idiots"]

In [39]:
np.array(my_list1)

array(['chatur', '3', 'idiots'], dtype='<U6')

In [40]:
bunny = [[1,2,3],[4,5]]
bunny_rabbit = np.array(bunny)


In [41]:
my_list1 = ["chatur", "rama", "linga"]

In [42]:
arrr1 = np.array(my_list1)

In [43]:
l = [[1,2],[3,4,5]]
a = np.array(l)
type(a)


numpy.ndarray

In [44]:
arrr1.dtype

dtype('<U6')

zeros and ones 
generate arrays of zeros and ones

In [10]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [45]:
np.zeros((6,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [46]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [47]:
a = np.ones(5)

In [48]:
a

array([1., 1., 1., 1., 1.])

In [49]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((6,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# linspace 
return evenly spaced numbers over a specified interval

In [15]:
a = np.linspace(0,100,5)
a

array([  0.,  25.,  50.,  75., 100.])

In [16]:
6.66666667-5

1.6666666699999997

In [17]:
8.3333333 + 1.66666

9.9999933

In [18]:
np.linspace(-1,0,10)

array([-1.        , -0.88888889, -0.77777778, -0.66666667, -0.55555556,
       -0.44444444, -0.33333333, -0.22222222, -0.11111111,  0.        ])

In [19]:
np.linspace(10,1000,3)

array([  10.,  505., 1000.])

In [20]:
np.linspace(10,1000,3)

array([  10.,  505., 1000.])

In [21]:
np.linspace(10,1000,1)

array([10.])

In [22]:
a = np.arange(10,50,1)
a.reshape(5,8)

array([[10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49]])

# eye
creates an indentity matrix below are some examples
All the elements of the matrix apart from the diagonal are zero.
the indentity matrix for any matrix is going to be a square matrix.

In [23]:
np.eye(4,) # this is a correct way to represent an identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random
Numpy also has various ways with which we can create array of random numbers (random number arrays)

An important part of any simulation is the ability to draw random numbers. For this purpose,
we use NumPy's built-in pseudorandom number generator routines in the sub-module
random. The numbers are pseudo random in the sense that they are generated
deterministically from a seed number, but are distributed in what has statistical similarities to
random fashion. NumPy uses a particular algorithm called the Mersenne Twister to generate
pseudorandom numbers.


The random number seed can be set:

np.random.seed(293423)
The seed is an integer value. Any program that starts with the same seed will generate exactly
the same sequence of random numbers each time it is run. This can be useful for debugging
purposes, but one does not need to specify the seed and in fact, when we perform multiple
runs of the same simulation to be averaged together, we want each such trial to have a
different sequence of random numbers. If this command is not run, NumPy automatically
selects a random seed (based on the time) that is different every time a program is run.


the first method is # rand 
which Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

# rand

#what is a unifrom distribution
#a uniform distribution is a set of variables that all have the exact same possibility of happening. 
#This uniform distribution, when displayed as a bar graph, has the exact same height of each bar and a standard number of bars. 
#In this way, it typically looks like a rectangle and therefore is often described as the rectangle distribution. 
#If you think about the possibility of pulling each suit's face card from a deck of playing cards, there is a random yet equal chance of pulling the jack of hearts as there is for pulling the king of spades.
 In statistics, a type of probability distribution in which all outcomes are equally likely.
#A deck of cards has a uniform distribution because the likelihood of drawing a heart, a club, a diamond or a spade is equally likely.
#A coin also has a uniform distribution because the probability of getting either heads or tails in a coin toss is the same.


In [24]:
np.random.rand(5) # the number 5 is how many numbers it will generate between 0 and 1 from a uniform distribution 



array([0.26915678, 0.650653  , 0.21382289, 0.64391862, 0.94916588])

In [25]:
np.random.rand(5,5)

array([[0.04918819, 0.77814579, 0.10854134, 0.82736604, 0.3030902 ],
       [0.11992356, 0.43523209, 0.56508709, 0.48909731, 0.32748402],
       [0.9733589 , 0.37205269, 0.39857655, 0.46917561, 0.70744604],
       [0.19488394, 0.95531529, 0.42498711, 0.63431016, 0.93714851],
       [0.11351132, 0.15943936, 0.91907223, 0.33987866, 0.66368998]])

In [26]:
np.random.rand(6,5)

array([[0.73179408, 0.73795752, 0.10436661, 0.9002899 , 0.58821719],
       [0.33406588, 0.46276539, 0.88338361, 0.70618154, 0.6937247 ],
       [0.38507816, 0.48994224, 0.36974751, 0.48992069, 0.06674017],
       [0.13750866, 0.49611971, 0.91235994, 0.30189525, 0.58403055],
       [0.79043394, 0.0479961 , 0.68371262, 0.34261328, 0.81562775],
       [0.08330604, 0.55612726, 0.77626519, 0.61324672, 0.11921664]])

In [27]:
np.random.rand(3,5)

array([[0.25413332, 0.19773416, 0.74012384, 0.47191019, 0.13573708],
       [0.95938146, 0.03374117, 0.42808044, 0.11568789, 0.11777717],
       [0.85492041, 0.99599584, 0.97050158, 0.00644235, 0.13558882]])

In [28]:
np.random.rand(1,1) # matrix with one row and one column

array([[0.01353056]])

# randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform
Properties of normal distribution :The standard normal distribution is a normal distribution with a:
mean of 0,
standard deviation of 1.

A normal distribution is a continuous probability distribution for a random variable x. The graph of a normal
distribution is called the normal curve, which has all of the following properties:
1. The mean, median, and mode are equal.
2. The normal curve is bell-shaped and is symmetric about the mean.
3. The total area under the curve is equal to one.
4. The normal curve approaches, but never touches, the x-axis.
5. Between µ − σ and µ + σ the graph is concave down and elsewhere the graph is concave up. The points at
which the graph changes concavity are called inflection points

In [29]:
np.random.randn(4) # again the the number 4 is the number of values it will generate.

array([-3.21194324e-01, -8.95939934e-01, -6.20349595e-04,  6.62511200e-01])

In [30]:
np.random.randn(6,4)

array([[ 0.55055222, -0.35657671, -2.41217405,  0.12552779],
       [-0.56085305,  0.468223  ,  1.66623878, -0.23736412],
       [-1.92327051,  1.19802957,  0.9102709 , -0.26663172],
       [-1.2667742 ,  0.26803829,  1.10406308, -0.37776204],
       [-0.51749578, -0.70394286,  1.42893051,  1.04573513],
       [ 2.25642224,  0.14023366,  1.07786474,  1.33699499]])

# randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [31]:
np.random.randint(1,10,10) # it will output a random integer in this case the default number of values it wil output is one 
#if you dont specify number of values you want in your output

array([9, 2, 3, 5, 7, 6, 3, 7, 2, 5])

In [32]:
ran = np.random.randint(10,100,20) # it will output ten integers between 10 to 100

In [33]:
np.random.randint(1,10,10)

array([8, 8, 3, 1, 7, 4, 3, 2, 1, 9])

In [34]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
ran

array([49, 77, 80, 45, 75, 29, 73, 31, 32, 12, 48, 39, 66, 19, 92, 23, 35,
       84, 60, 81])

In [46]:
ran.reshape(20)

array([49, 77, 80, 45, 75, 29, 73, 31, 32, 12, 48, 39, 66, 19, 92, 23, 35,
       84, 60, 81])

ValueError: cannot resize this array: it does not own its data

In [44]:
ran = ran.reshape(4,5)
ran

array([[49, 77, 80, 45, 75],
       [29, 73, 31, 32, 12],
       [48, 39, 66, 19, 92],
       [23, 35, 84, 60, 81]])

In [361]:
ar4 = np.arange(0,51)

###### This is also one very good example below to understand details of random and reshape

In [43]:
np.random.randint(4,1000,20)

array([655, 839, 369, 265, 945, 117, 425, 323, 222, 970, 808, 945, 436,
       802, 295, 820, 593, 874, 752, 560])

In [46]:
np.random.randint(4,1000,20).reshape(5,4)

array([[658, 278,  35, 714],
       [545, 130, 123, 299],
       [707, 889, 862,  88],
       [775, 616, 446, 909],
       [848, 680, 460, 306]])

# Array Attributes and Methods

here we will see some useful methods and attributes of array

In [37]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranarr

array([44,  4, 38, 49, 40, 24, 35, 47, 45, 22])

#  Reshape
Returns an array containing the same data with a new shape.

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

###### one important thing elements in the array should match the arguments you pass in the array.
#in the above case it was (5,5) and there were 25 elements.

In [40]:
arr.reshape(5,4) # here is the example of what happens

ValueError: cannot reshape array of size 25 into shape (5,4)

In [41]:
ranarr.reshape(5,2)

array([[ 8, 26],
       [46, 21],
       [27, 25],
       [33, 19],
       [43, 29]])

# max,min,argmax,argmin
These are useful methods for finding max or min values. 

argmax and argmin are used for finding index location of the max value and the minimum value.

In [28]:
ranarr = np.random.randint(0,50,10)
ranarr

array([43, 33, 39, 45, 30, 30, 19, 45, 44, 13])

In [29]:
ranarr.max()

45

In [30]:
ranarr.min()

13

In [31]:
ranarr.argmax()

3

In [32]:
ranarr.argmin()

9

# Shape 

In [212]:
# shape is used for getting the shape of array, whether it is one dimensional or two dimensional

In [213]:
arr.shape

(25,)

In [214]:
# if we want we can reshape it with our reshape method

In [215]:
ranarr.shape

(10,)

In [216]:
# this marks the end of array first chapter.

# concatinate

In [223]:
a = np.array([1, 2, 3])
b = np.array([5, 6])
c= np.concatenate([a, b]) 

In [224]:
c

array([1, 2, 3, 5, 6])

In [225]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)



array([[1, 2],
       [3, 4],
       [5, 6]])

In [227]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [7]:
np.linspace(0,11,2)

array([  0.,  11.])

In [7]:
my_mat = [[[1,2,3],[3,4,5],[7,8,9]]]

In [8]:
np.array(my_mat)

array([[[1, 2, 3],
        [3, 4, 5],
        [7, 8, 9]]])

In [58]:
a = arr.reshape(5,5)

In [60]:
a.max()

24

In [ ]:
import os 
os.chdir()